
source 'https://github.com/hj04210037/HJ_Seed_Spec.git'
source 'https://github.com/CocoaPods/Specs.git'


use_frameworks!


platform :ios, '9.0'

target 'privateLibrary_Example' do
  pod 'privateLibrary', :path => '../'

  target 'privateLibrary_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
